# Default values for readsb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

readsb:
  # Set to any value to apply a 1Hz DC filter to input data (requires more CPU)
  dcfilter: false

  # If using an SDR, set this to rtlsdr, bladerf, modesbeast, gnshulc or plutosdr depending on the model of your SDR. If not using an SDR, leave un-set.
  #deviceType: rtlsdr

  #Set to any value to enable CRC single-bit error correction
  fix: false

  # Set this to any value to allow forwarding of received mlat results to output ports.
  # Leave this unset unless you know what you're doing.
  forwardMlat: false

  #Set frequency (in MHz)
  #freq: 1090

  # Set this to any value to display raw messages in Beast ASCII mode
  mlat: false

  #Set gain (in dB). Use autogain to have the container determine an appropriate gain, more on this below.
  #gain: autogain



  # modeac: true
  # rxLocationAccuracy: 2
  # statsRange: true
  # disableWebApp: true
  # disablePerformanceGraphs: true
  # forwardMlat: true
  # net:
  #   enable: true
  #   only: true
  #   connector: piaware,30105,beast_in;adsbx,30105,beast_in;rbfeeder,30105,beast_in

#location:
#  longitude: "59.0"
#  latitude: "17.0"



#influxdb:
#  url: http://influxdb:8086
#  username: admin
#  password: admin123

securityContext:
  privileged: true

# Path to your piaware device in the container
#additionalVolumeMounts:
#  - name: usb
#    mountPath: /dev/bus/usb/001/005

# Path to your piaware device on the host
#additionalVolumes:
#  - name: usb
#    hostPath:
#      path: /dev/bus/usb/001/005

image:
  repository: mikenye/readsb-protobuf
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

service:
  type: ClusterIP
  http:
    port: 8080
  sbs:
    port: 30003
  raw:
    port: 30002
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
