apiVersion: v1
kind: Service
metadata:
  name: {{ include "readsb.fullname" . }}
  labels:
    {{- include "readsb.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ (((.Values.readsb).net).beast).outputPort | default 30005 }}
      targetPort: beast
      protocol: TCP
      name: beast
    - port: {{ .Values.service.sbs.port }}
      targetPort: sbs
      protocol: TCP
      name: sbs
    - port: {{ .Values.service.raw.port }}
      targetPort: raw
      protocol: TCP
      name: raw
    - port: 9273
      targetPort: metrics
      protocol: TCP
      name: metrics

  selector:
    {{- include "readsb.selectorLabels" . | nindent 4 }}
