{
 "title": "Flight stats from dump 1090",
 "description": "This dashboard displays dump1090 metrics that get exposed to Prometheus by the dump1090exporter.",
 "tags": [ "flight" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Aircraft Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_observed{job=\"dump1090-exporter\", time_period=\"latest\"}"
    }
   ]
  },
  {
   "title": "Aircraft w/ Position",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_with_position{job=\"dump1090-exporter\", time_period=\"latest\"}"
    }
   ]
  },
  {
   "title": "Max Range",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "lengthm",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_max_range{job=\"dump1090-exporter\"}"
    }
   ]
  },
  {
   "title": "Messages/Sec",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(dump1090_messages_total{job=\"dump1090-exporter\", time_period=\"latest\"}[1m])"
    }
   ]
  },
  {
   "title": "Signal Peak",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dump1090_stats_local_peak_signal_strength_dbFS{job=\"dump1090-exporter\", time_period=\"last1min\"}"
    }
   ]
  },
  {
   "title": "Signal Mean",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dump1090_stats_local_signal_strength_dbFS{job=\"dump1090-exporter\", time_period=\"last1min\"}"
    }
   ]
  },
  {
   "title": "Aircraft",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_observed{job=\"dump1090-exporter\", time_period=\"latest\"}",
     "legendFormat": "total"
    },
    {
     "expr": "dump1090_recent_aircraft_with_position{job=\"dump1090-exporter\", time_period=\"latest\"}",
     "legendFormat": "W/ position"
    },
    {
     "expr": "dump1090_recent_aircraft_observed{job=\"dump1090-exporter\", time_period=\"latest\"} - dump1090_recent_aircraft_with_position{job=\"dump1090\", time_period=\"latest\"}",
     "legendFormat": "Wo/ position"
    },
    {
     "expr": "dump1090_recent_aircraft_with_multilateration{job=\"dump1090-exporter\", time_period=\"latest\"}",
     "legendFormat": "mlat"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "options": {
    "content": "#### Aircraft\nThis graph displays the counts of aircraft (e.g unique ICAO) being reported. Aircraft are grouped into total aircraft being reported, aircraft reported with a position, aircraft reported without a position and aircraft reported that have multi-lateration reports."
   },
   "content": "#### Aircraft\nThis graph displays the counts of aircraft (e.g unique ICAO) being reported. Aircraft are grouped into total aircraft being reported, aircraft reported with a position, aircraft reported without a position and aircraft reported that have multi-lateration reports."
  },
  {
   "title": "Maximum Range",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_max_range{job=\"dump1090-exporter\", time_period=\"latest\"}",
     "legendFormat": "{{ time_period }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "options": {
    "content": "##### Maximum Range\nThis graph displays the maximum range of the currently observed aircraft reporting a position."
   },
   "content": "##### Maximum Range\nThis graph displays the maximum range of the currently observed aircraft reporting a position."
  },
  {
   "title": "messages / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dump1090_messages_total{job=\"dump1090-exporter\", time_period=\"latest\"}[1m])",
     "legendFormat": "latest"
    },
    {
     "expr": "dump1090_stats_messages_total{job=\"dump1090-exporter\", time_period=\"last1min\"} / 60",
     "legendFormat": "last1min"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "options": {
    "content": "##### Messages\nThis graph displays the messages received per second."
   },
   "content": "##### Messages\nThis graph displays the messages received per second."
  },
  {
   "title": "Signal Strength",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "dbFS" }
   ],
   "targets": [
    {
     "expr": "dump1090_stats_local_signal_strength_dbFS{job=\"dump1090-exporter\", time_period=\"last1min\"}",
     "legendFormat": "mean"
    },
    {
     "expr": "dump1090_stats_local_peak_signal_strength_dbFS{job=\"dump1090-exporter\", time_period=\"last1min\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "dump1090_stats_local_noise_level_dbFS{job=\"dump1090-exporter\", time_period=\"last1min\"}",
     "legendFormat": "noise"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "options": {
    "content": "##### Signal Strength\nThis graph displays the signal levels reported for noise, mean and peak signal levels. The values are reported in [dbFS](https://en.wikipedia.org/wiki/DBFS)."
   },
   "content": "##### Signal Strength\nThis graph displays the signal levels reported for noise, mean and peak signal levels. The values are reported in [dbFS](https://en.wikipedia.org/wiki/DBFS)."
  },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "dump1090_stats_cpu_demod_milliseconds{job=\"dump1090-exporter\", time_period=\"last1min\"}",
     "legendFormat": "demod"
    },
    {
     "expr": "dump1090_stats_cpu_reader_milliseconds{job=\"dump1090-exporter\", time_period=\"last1min\"}",
     "legendFormat": "usb"
    },
    {
     "expr": "dump1090_stats_cpu_background_milliseconds{job=\"dump1090-exporter\", time_period=\"last1min\"}",
     "legendFormat": "other"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "options": {
    "content": "##### CPU Utilisation\nThis graph displays how much CPU time is used by the dump1090 tool. demod reports the time spent demodulating and decoding data from the USB SDR dongle. usb reports time spent reading sample data from the USB SDR dongle. other reports time spent doing network I/O, processing network messages, and periodic tasks.\n"
   },
   "content": "##### CPU Utilisation\nThis graph displays how much CPU time is used by the dump1090 tool. demod reports the time spent demodulating and decoding data from the USB SDR dongle. usb reports time spent reading sample data from the USB SDR dongle. other reports time spent doing network I/O, processing network messages, and periodic tasks.\n"
  }
 ]
}