apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "piaware.fullname" . }}
  labels:
    {{- include "piaware.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "piaware.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "piaware.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "piaware.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TZ
              value: "{{ .Values.timezone }}"
            - name: LAT
              value: "{{ .Values.location.latitude }}"
            - name: LONG
              value: "{{ .Values.location.longitude }}"
            - name: BEASTHOST
              value: "{{ .Values.beast.host }}"
            - name: BEASTPORT
              value: "{{ .Values.beast.port }}"
            - name: FEEDER_ID
              value: "{{ .Values.feederKey }}"

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: beast
              containerPort: 30005
              protocol: TCP
            - name: mlat
              containerPort: 30105
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
