apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adsb-exchange.fullname" . }}
  labels:
    {{- include "adsb-exchange.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "adsb-exchange.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "adsb-exchange.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "adsb-exchange.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TZ
              value: "{{ .Values.timezone}}"
            - name: BEASTHOST
              value: "{{ .Values.beast.host }}"
            - name: BEASTPORT
              value: "{{ .Values.beast.port }}"
            - name: LAT
              value: "{{ .Values.location.latitude }}"
            - name: LONG
              value: "{{ .Values.location.longitude }}"
            - name: ALT
              value: "{{ .Values.location.altitude }}"
            - name: SITENAME
              value: "{{ .Values.sitename }}"
            - name: UUID
              value: "{{ .Values.uuid }}"
          ports:
            - name: mlat
              containerPort: 30105
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
