apiVersion: v1
kind: Service
metadata:
  name: {{ include "adsb-exchange.fullname" . }}
  labels:
    {{- include "adsb-exchange.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mlat
      protocol: TCP
      name: mlat
  selector:
    {{- include "adsb-exchange.selectorLabels" . | nindent 4 }}
